{% set version = "0.4.1" %}
package:
  name: "raw2ometiff"
  version: "{{ version }}"

build:
  number: 0

source:
  url: https://github.com/glencoesoftware/raw2ometiff/releases/download/v{{ version
    }}/raw2ometiff-{{ version }}.zip
  sha256: 1c7f76eeae3de758ee5f844d9e1455aa34b4d4d65fcd6e2a07b710ce7f2aff30
  patches:
  - windows-bat-classpath-wildcard.patch    # [win]

requirements:
  run:
  - raw2ometiff-libs={{ PKG_VERSION }}-{{ PKG_BUILDNUM }}
  - openjdk

test:
  commands:
  - raw2ometiff --help

extra:
  recipe-maintainers:
  - ome

about:
  home: https://www.openmicroscopy.org/
  license: GNU General Public v2 or later (GPLv2+)
  license_family: GPL2
  summary: Raw format to OME-TIFF converter
  dev_url: https://github.com/glencoesoftware/raw2ometiff/
