{% set version = "0.3.0" %}
package:
  name: "raw2ometiff"
  version: "{{ version }}"

build:
  number: 0

source:
  url: https://github.com/glencoesoftware/raw2ometiff/releases/download/v{{ version }}/raw2ometiff-{{ version }}.zip
  sha256: 0731dc3e03b23ac90d38eab45dc57e71db7db1219a189aac0be97f1116fc2fa1

requirements:
  run:
    - raw2ometiff-libs={{ PKG_VERSION }}-{{ PKG_BUILDNUM }}
    - openjdk

test:
  commands:
    - raw2ometiff --help

extra:
  recipe-maintainers:
    - ome

about:
  home: https://www.openmicroscopy.org/
  license: GNU General Public v2 or later (GPLv2+)
  license_family: GPL2
  summary: Raw format to OME-TIFF converter
  dev_url: https://github.com/glencoesoftware/raw2ometiff/
