{% set version = "0.3.0rc3" %}
{% set github_version = "0.3.0-rc3" %}
package:
  name: "raw2ometiff-libs"
  version: "{{ version }}"

build:
  number: 0
  noarch: generic

source:
  url: https://github.com/glencoesoftware/raw2ometiff/releases/download/v{{ version }}/raw2ometiff-{{ github_version }}.zip
  sha256: 7e58e616d39b8af5cfb9081747436c3f3dfbe20cd377c54b15687cbeb1bec0e6

# Leave the general dependencies to the wrapper
requirements:

extra:
  recipe-maintainers:
    - ome

about:
  home: https://www.openmicroscopy.org/
  license: GNU General Public v2 or later (GPLv2+)
  license_family: GPL2
  summary: Raw format to OME-TIFF converter
  dev_url: https://github.com/glencoesoftware/raw2ometiff/
